---
# tasks file for web
    - name: 'Instalação de pacotes da aplicação'
      apt:
        pkg:
          - php7.0
          - php-pear
          - php7.0-curl
          - php7.0-gd
          - php7.0-intl
          - php7.0-xmlrpc
          - php7.0-mysql
          - apache2
          - wget
          - zip
          - curl
          - vim
        state: present
        update_cache: yes
    - name: 'Cria pasta do webserver se não existe'
      file:
        path: /srv/www
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
    - name: 'Download e extração do conteúdo da aplicação'
      unarchive:
        src: https://github.com/rogerramossilva/devops/raw/master/express.zip
        dest: /srv/www
        remote_src: yes
        validate_certs: no
    - name: 'Substitui ip de conexão com o banco'
      replace:
        path: /srv/www/express/backup.php
        regexp: '192\.168\.1\.20'
        replace: '172.17.177.101'
    - name: 'Cria arquivo de configuração do diretório da página express'
      template:
        src: 'files/express.conf'
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
    - name: 'Criando directory para controle do express'
      template:
        src: 'files/direxpress.conf'
        dest: '/etc/apache2/conf-available/direxpress.conf'
    - name: 'Ajusta o arquivo /etc/hosts para resolver nome'
      template:
        src: 'files/hostsintranet'
        dest: '/etc/hosts'
    - name: 'Habilita site'
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: restart apache
    - name: 'Habilita configuração do direxpress'
      shell: /usr/sbin/a2enconf direxpress.conf
      notify: restart apache
    - name: 'Habilitar modulo do virtualhost'
      apache2_module:
        name: "{{ item }}"
        state: present
      loop: "{{ modsapache }}"
      notify: restart apache
    - name: 'Ajuste de permissão da aplicação para usuário www-data'
      file:
        path: /srv/www/express
        state: directory
        recurse: yes
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
    - name: 'Ajuste de ip de conexão com o banco errado'
      replace:
        path: /srv/www/express/backup.php
        regexp: '172\.17\.177\.101'
        replace: '172.17.177.102'