---
- hosts: intranet
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: 'Instalação de pacotes da aplicação'
      apt:
        pkg:
          - php7.0
          - php-pear
          - php7.0-curl
          - php7.0-gd
          - php7.0-intl
          - php7.0-xmlrpc
          - php7.0-mysql
          - apache2
          - wget
          - zip
          - curl
          - vim
        state: present
        update_cache: yes
    - name: 'Cria pasta do webserver se não existe'
      file:
        path: /srv/www
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
    - name: 'Download e extração do conteúdo da aplicação'
      unarchive:
        src: https://github.com/rogerramossilva/devops/raw/master/express.zip
        dest: /srv/www
        remote_src: yes
        validate_certs: no
    - name: 'Substitui ip de conexão com o banco'
      replace:
        path: /srv/www/express/backup.php
        regexp: '192\.168\.1\.20'
        replace: '172.17.177.101'
    - name: 'Cria arquivo de configuração do diretório da página express'
      template:
        src: 'files/express.conf'
        dest: "/etc/apache2/sites-available/{{ http_conf }}"